# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Volumes/cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Volumes/cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Nancy/Desktop/fluidsolver/CIS563-FluidSolver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Nancy/Desktop/fluidsolver/CIS563-FluidSolver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Volumes/cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Volumes/cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Nancy/Desktop/fluidsolver/CIS563-FluidSolver/CMakeFiles /Users/Nancy/Desktop/fluidsolver/CIS563-FluidSolver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Nancy/Desktop/fluidsolver/CIS563-FluidSolver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Thanda

# Build rule for target.
Thanda: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Thanda
.PHONY : Thanda

# fast build rule for target.
Thanda/fast:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/build
.PHONY : Thanda/fast

src/camera/camera.o: src/camera/camera.cpp.o

.PHONY : src/camera/camera.o

# target to build an object file
src/camera/camera.cpp.o:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/camera/camera.cpp.o
.PHONY : src/camera/camera.cpp.o

src/camera/camera.i: src/camera/camera.cpp.i

.PHONY : src/camera/camera.i

# target to preprocess a source file
src/camera/camera.cpp.i:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/camera/camera.cpp.i
.PHONY : src/camera/camera.cpp.i

src/camera/camera.s: src/camera/camera.cpp.s

.PHONY : src/camera/camera.s

# target to generate assembly for a file
src/camera/camera.cpp.s:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/camera/camera.cpp.s
.PHONY : src/camera/camera.cpp.s

src/fluidSolver/fluidSolver.o: src/fluidSolver/fluidSolver.cpp.o

.PHONY : src/fluidSolver/fluidSolver.o

# target to build an object file
src/fluidSolver/fluidSolver.cpp.o:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/fluidSolver/fluidSolver.cpp.o
.PHONY : src/fluidSolver/fluidSolver.cpp.o

src/fluidSolver/fluidSolver.i: src/fluidSolver/fluidSolver.cpp.i

.PHONY : src/fluidSolver/fluidSolver.i

# target to preprocess a source file
src/fluidSolver/fluidSolver.cpp.i:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/fluidSolver/fluidSolver.cpp.i
.PHONY : src/fluidSolver/fluidSolver.cpp.i

src/fluidSolver/fluidSolver.s: src/fluidSolver/fluidSolver.cpp.s

.PHONY : src/fluidSolver/fluidSolver.s

# target to generate assembly for a file
src/fluidSolver/fluidSolver.cpp.s:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/fluidSolver/fluidSolver.cpp.s
.PHONY : src/fluidSolver/fluidSolver.cpp.s

src/geom/geom.o: src/geom/geom.cpp.o

.PHONY : src/geom/geom.o

# target to build an object file
src/geom/geom.cpp.o:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/geom/geom.cpp.o
.PHONY : src/geom/geom.cpp.o

src/geom/geom.i: src/geom/geom.cpp.i

.PHONY : src/geom/geom.i

# target to preprocess a source file
src/geom/geom.cpp.i:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/geom/geom.cpp.i
.PHONY : src/geom/geom.cpp.i

src/geom/geom.s: src/geom/geom.cpp.s

.PHONY : src/geom/geom.s

# target to generate assembly for a file
src/geom/geom.cpp.s:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/geom/geom.cpp.s
.PHONY : src/geom/geom.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/scene/scene.o: src/scene/scene.cpp.o

.PHONY : src/scene/scene.o

# target to build an object file
src/scene/scene.cpp.o:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/scene/scene.cpp.o
.PHONY : src/scene/scene.cpp.o

src/scene/scene.i: src/scene/scene.cpp.i

.PHONY : src/scene/scene.i

# target to preprocess a source file
src/scene/scene.cpp.i:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/scene/scene.cpp.i
.PHONY : src/scene/scene.cpp.i

src/scene/scene.s: src/scene/scene.cpp.s

.PHONY : src/scene/scene.s

# target to generate assembly for a file
src/scene/scene.cpp.s:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/scene/scene.cpp.s
.PHONY : src/scene/scene.cpp.s

src/viewer/viewer.o: src/viewer/viewer.cpp.o

.PHONY : src/viewer/viewer.o

# target to build an object file
src/viewer/viewer.cpp.o:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/viewer/viewer.cpp.o
.PHONY : src/viewer/viewer.cpp.o

src/viewer/viewer.i: src/viewer/viewer.cpp.i

.PHONY : src/viewer/viewer.i

# target to preprocess a source file
src/viewer/viewer.cpp.i:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/viewer/viewer.cpp.i
.PHONY : src/viewer/viewer.cpp.i

src/viewer/viewer.s: src/viewer/viewer.cpp.s

.PHONY : src/viewer/viewer.s

# target to generate assembly for a file
src/viewer/viewer.cpp.s:
	$(MAKE) -f CMakeFiles/Thanda.dir/build.make CMakeFiles/Thanda.dir/src/viewer/viewer.cpp.s
.PHONY : src/viewer/viewer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Thanda"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/camera/camera.o"
	@echo "... src/camera/camera.i"
	@echo "... src/camera/camera.s"
	@echo "... src/fluidSolver/fluidSolver.o"
	@echo "... src/fluidSolver/fluidSolver.i"
	@echo "... src/fluidSolver/fluidSolver.s"
	@echo "... src/geom/geom.o"
	@echo "... src/geom/geom.i"
	@echo "... src/geom/geom.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scene/scene.o"
	@echo "... src/scene/scene.i"
	@echo "... src/scene/scene.s"
	@echo "... src/viewer/viewer.o"
	@echo "... src/viewer/viewer.i"
	@echo "... src/viewer/viewer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

